### ISSUE TITLE
Combine multiscalar multiplications in constraint system proof verification

### ISSUE THREAD

**Issue by hdevalence** [dalek-cryptography/bulletproofs#148]
The current constraint system verify implementation does multiple multiscalar multiplications; these could all be batched together into a single multiscalar multiplication using random values.

**Comment by cathieyun** [comment]
For the `W_L_point`, `W_R_point`, `W_O_point` calculations:
- Inlining `W_O_point` is easy, and does not require a challenge scalar, seen here: https://github.com/dalek-cryptography/bulletproofs/pull/159
- Inlining `W_L_point` and `W_O_point` are actually really tricky because they are used in the `P` check (line 87), but they are also used to calculate delta which is then used in the `t` check (line 85). I don't think there's a clean way to do that...
- We could combine the `H_prime` calculation with the `W_L_point` calculation, but then we'd have to calculate `H_prime` again for the `W_O_point` calculation so I think it still makes sense to calculate that upfront. (

**Comment by hdevalence** [comment]
> Inlining `W_O_point` is easy

Great!

> Inlining `W_L_point` and `W_O_point` are actually really tricky...

I guess you mean `W_R_point` (typo)? I'm not sure where the points are used in the computation of `delta` -- it looks to me like `delta` is computed just in terms of the scalars used to compute `W_R` and `W_L`, without using the points themselves, so it seems like it should be possible?

> We could combine the `H_prime` calculation with the `W_L_point` calculation, but then we'd have to calculate `H_prime` again for the `W_O_point` calculation so I think it still makes sense to calculate that upfront.

When we combine the calculations, we pay only the cost of an extra scalar/scalar multiplication for each scalar/point term in the multiscalar multiplication, but we save a full scalar/point multiplication by not computing H'.  But since a scalar/scalar multiplication is a couple hundred times cheaper than a scalar/point multiplication, I think it's still a big saving to avoid computing H'.

**Comment by oleganza** [comment]
Status update:

* #184 adds notes on how the mega check is formed
* #159 implements that mega check

**Comment by oleganza** [comment]
#159 finished and merged. Notes in #184 are merged.
