### ISSUE TITLE
Implement serialization for `R1CSProof`s

### ISSUE THREAD

**Issue by hdevalence** [dalek-cryptography/bulletproofs#214]
The `R1CSProof` should have a serialization format; the `RangeProof` code could be a good example.

**Comment by rubdos** [comment]
Any special requests for this? I'll mimic the implementation from `RangeProof` and adapt it for `R1CSProof`. I'd like to know the serialized_size in my experiments, so I'll drop in a method for that too.

**Comment by oleganza** [comment]
There is an open question on whether/how we need to distinguish between the proofs that use randomization and those that don't: https://github.com/dalek-cryptography/bulletproofs/issues/242

Since the R1CS is specified statically by the code, and not by the proof, we don't need any flag whatsoever. However, users of proofs that don't use randomization may want to save 96 bytes (`A_I2, A_O2, S2` commitments) and replace them with a single-byte flag, so that the proof created by a system that doesn't allow randomization can be verified by a system that does (and not hiccup on parsing the proof). I personally would keep things simple and not attempt to save those 96 bytes. If you are doing a R1CS ZK proof, especially, w/o randomization, these 96 bytes would be a drop in the ocean.

**Comment by rubdos** [comment]
> I personally would keep things simple and not attempt to save those 96 bytes. If you are doing a R1CS ZK proof, especially, w/o randomization, these 96 bytes would be a drop in the ocean.

In my current (*extremely simple*) experiment, I had a proof size of 800B, including commitments. Those 96 bytes would be over 10%, but I was already using challenges... :-)

**Comment by oleganza** [comment]
You see: challenges save space in permutation gadgets and composition of boolean statements, but use extra 96 bytes. If you don’t use challenges, you either blow up your proof size (permutation would require ~n^2 multipliers instead of 2n), or you are doing smth like sha256 proof where number of multipliers and individual commitments is so big that there is no point in saving 96 bytes.

**Comment by oleganza** [comment]
Oh, i apologize: the BP paper mentions that sha256 proof uses 25K multipliers, and the proof is just 1376 bytes. So, indeed, 96 bytes are not nothing :-/

Ok, lets add some flag.

**Comment by rubdos** [comment]
I'll need some guidance here then; when deserializing, what should be the contents of  the `A_I2, A_O2, S2` commitments if the flag is set?

Then: an extra byte for flags seems expensive; can't we leave it to the user whether he wants the randomization compiled in? 

> so that the proof created by a system that doesn't allow randomization can be verified by a system that does (and not hiccup on parsing the proof)

I agree with the sentiment here; but how often would this happen? Most of the time, these kind of things are known on a protocol level, and can "just" be flagged through to the system, no?
