### ISSUE TITLE
R1CS: Closure of challenge phase is `Fn`.

### ISSUE THREAD

**Issue by rubdos** [dalek-cryptography/bulletproofs#244]
Since #222, one writes the challenge phase using a closure. This closure gets stored in a `Vec<Box<Fn(...)>>`, and then gets called once at the start of the second phase.

Ideally, this closure should be `FnOnce`, such that it's able to consume some of its context (e.g. a set of variables could be consumed instead of borrowed).

Note that it is **currently impossible** to call a `Box<FnOnce>`, because it would call a method with unsized self. Cfr. https://github.com/rust-lang/rust/issues/28796

Nightly does support `FnBox()`, which is a temporary workaround. The above issue is discussion deprecation of `FnBox()` in favour of the `unsized_locals` feature (which makes `Box<FnOnce>` callable).

---

Note that there does not seem to be a fix for stable Rust, but I thought this should be noted somewhere. I'm not sure whether you are in favour of keeping this issue open while waiting for [`unsized_locals` stabilization](https://github.com/rust-lang/rust/issues/48055).

**Comment by oleganza** [comment]
Thanks for opening this issue and explaining the context behind `Box<Fn>`. I think it makes total sense to keep it open until there is a fix for `Box<FnOnce>`.

**Comment by oleganza** [comment]
Since we have to use nightly for other reasons (non-lexical lifetimes in IPP `nll`), and that `Box<FnOnce>` is getting [stabilized in Rust 1.35](https://github.com/rust-lang/rust/issues/28796#issuecomment-481502369) (next release), we could probably change the API now and throw in a `#![feature(unsized_locals)]` until 1.35.

**Comment by cathieyun** [comment]
That sounds good to me! As long as we remember to remove `unsized_locals` when 1.35 comes out so we have fewer nightly dependencies.

**Comment by hdevalence** [comment]
+1 to all of the above. One thing we could do is to make the `unsized_locals` only enabled when the `yoloproofs` (which can be renamed to `r1cs` or something later if we decide it's not yolo), so that it's only pulled in for the r1cs code rather than for the rangeproof code.  It might also be good to check on the NLL status.

**Comment by oleganza** [comment]
Seems like NLL is stable since 1.31: https://blog.rust-lang.org/2018/12/06/Rust-1.31-and-rust-2018.html#non-lexical-lifetimes

**Comment by rubdos** [comment]
Closed through #276
