### ISSUE TITLE
Longer-term proof protocols with suspend and resume.

### ISSUE THREAD

**Issue by rubdos** [dalek-cryptography/bulletproofs#250]
Original issue on https://github.com/dalek-cryptography/merlin/issues/35.
Merlin allows for "Interactive composition of noninteractive proofs", but I wonder whether it's possible to use previously committed values in future proofs.
More concretely, I wonder whether it is possible and sound to do the following (in context of R1CS, mostly):

- Commit to a bunch of values
- Suspend the proof, wait a few days
- Use the commitments in a R1CS proof (and maybe also in a RangeProof)

In particular: this would mean that committing values and creating `Variables` in a R1CS proof system should be possible to happen in separate calls.

Does this make sense?

**Comment by oleganza** [comment]
It only makes sense to create Pedersen commitments for each value upfront, and then later re-commit them during proving (you’d need the secrets on hand nonetheless). 

As of suspending the transcript mid-way, it does not make sense (to me, at least) because the verifier must also be meaningfully suspended which would turn a noninteractive protocol into an interactive one.

**Comment by hdevalence** [comment]
Hi!

I don't have any good ideas because I'm not quite sure exactly what the goal is.  I don't think it's a good idea to try to pause the Bulletproofs protocol mid-way and I'm not clear on exactly why you'd want to.

The idea from the blog post is slightly different: it's for the next-higher level above the individual "proof components" (like a Bulletproof); for instance, you could imagine you and your counterparty trading range proofs back and forth (for a payment channel or something) and those proofs could be bound together per-session to prevent replay attacks or something.

**Comment by rubdos** [comment]
It helps; at least it seems like I did understand the blog post correctly. :-)

Although, I can imagine such a back-and-forth communication, where, at some point you want to use a value that you committed to earlier on in the protocol.

Imagine for example what happens in [this paper](https://www.tipsystems.nl/files/ETPprivacy.pdf), where a citizen and a government are exchanging information for electronic traffic pricing. In the presented protocol, the citizen first commits to their travelled route and sends over the commitments to the government. Then - to ensure the citizen is not lying - the government sends back their "spot checks": the citizen has been seen on a few random locations in the country. Now the citizen has to prove that their commitments to the route somehow match the spot checks. Note that both transmissions of the citizen could contain a proof: "this is a valid route" (1) and "I was indeed at the location where you've seen me" (2).

In general, I think there will be more examples where certain input for the proof should only be made available after having committed to certain values.

**Comment by rubdos** [comment]
A few comments:

- It is perfectly possible to "re-commit" to previous commitments, since the API requires me to pick the blinding factor myself. Which at least makes this issue about "maybe provide a better API for this case", but I don't think that's even possible.
- Suspending a transcript makes sense if it's semantically meaningful, and it's entirely possible through extracting from the transcript, and initialising a new transcript with these bytes.
- I could use an interactive zk protocol, but bulletproofs are way too efficient to do so. Using the interactive description of bulletproofs seems dangerous, since I don't know of any proof for ***dis**honest verifier zero-knowledge*.

Given all of the above, I am okay with closing this issue. I think it boiled down to me misinterpreting @oleganza's comment:

> It only makes sense to create Pedersen commitments for each value upfront, and then later re-commit them during proving (you’d need the secrets on hand nonetheless).

which means that keeping track of the blinding factors is *my* responsibility, not the transcript's! :-)
