### ISSUE TITLE
travisci failed at yoloproofs

### ISSUE THREAD

**Issue by HaoXuan40404** [dalek-cryptography/bulletproofs#293]
I found that the latest code at .travis.yml added FEATURES='yoloproofs'，but run `cargo test --features='yoloproofs'` will be failed

**Comment by HaoXuan40404** [comment]
Like this 
![image](https://user-images.githubusercontent.com/34049754/62369311-d3b7bd00-b561-11e9-89dd-caacd9594b0f.png)

**Comment by hdevalence** [comment]
Ah, thanks for noticing this.

The problem is that the development branch `develop` has the `yoloproofs` feature to enable the R1CS API, but because we don't want people to depend on it in the published crate yet, it's commented out in the `main` branch and the published crate.  So I guess the CI is failing only on the `main` branch and still working on the `develop` branch, right?

**Comment by HaoXuan40404** [comment]
Hah, you're right. I built it on develop, and it succeeds. Maybe FEATURES='yoloproofs' should be hidden at main?

**Comment by hdevalence** [comment]
Yes, I think so. That change should have been included in 08a713e885a6256d62ce244a9f61826238d51534 but it wasn't.  I can commit it as a fixup commit.

**Comment by hdevalence** [comment]
Hopefully fixed in 4b9d2c9

**Comment by HaoXuan40404** [comment]
Ok, thank you
